# Generated by Django 3.1.2 on 2020-10-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('platform', models.PositiveSmallIntegerField(null=True)),
                ('soft_delete', models.PositiveSmallIntegerField(default=0)),
                ('emp_id', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.menuitems')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
