# Generated by Django 3.1.2 on 2020-10-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name_plural': 'Party items'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'INITIALIZED'), (1, 'ACTIVE'), (2, 'ORDER_CLOSED')], default=0),
        ),
    ]
