# Generated by Django 3.1.2 on 2020-10-11 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0004_auto_20201011_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='party',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='party.party'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='party.employee'),
            preserve_default=False,
        ),
    ]
