# Generated by Django 3.1.2 on 2020-10-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0007_auto_20201011_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ADDED'), (0, 'DELETED')], default=1),
        ),
    ]
