# Generated by Django 3.1.2 on 2020-10-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0008_auto_20201011_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item',
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('platform', models.PositiveSmallIntegerField(null=True)),
                ('soft_delete', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.menuitems')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.orders')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
