# Generated by Django 3.1.2 on 2020-10-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0009_auto_20201011_1828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitems',
            unique_together={('order', 'item')},
        ),
    ]
