# Generated by Django 3.1.2 on 2020-10-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0010_auto_20201011_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'OPEN'), (0, 'CLOSED')], default=1),
        ),
    ]
