# Generated by Django 3.1.2 on 2020-10-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0011_auto_20201011_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=1),
        ),
    ]
