# Generated by Django 3.1.2 on 2020-10-11 19:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0012_auto_20201011_1856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('employee', 'party')},
        ),
    ]
