# Generated by Django 3.1.2 on 2020-10-11 20:10

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0013_auto_20201011_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='party.party'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='party', chained_model_field='party', on_delete=django.db.models.deletion.CASCADE, to='party.menuitems'),
        ),
    ]
