# Generated by Django 3.1.2 on 2020-10-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0016_auto_20201011_2027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orders',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='party',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
