# Generated by Django 3.1.2 on 2020-10-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0017_auto_20201011_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='neworder',
            unique_together=set(),
        ),
    ]
